### ISSUE TITLE
JupyterLab Forces Dark Theme

### ISSUE THREAD

**Issue by manfromjupyter** [nbgallery/lab-extensions#10]
Every time my jupyterlab restarts with this extension it resets the theme I set.  Sometimes I prefer the lighter theme and would like it to remember. Anyway was curious if there was a way to force this as a workaround or if not if we could do something about that and have it rememeber.

**Comment by mcrutch** [comment]
Restarts? or when an entirely new Jupyter environment is created?  Because Lab defaults to light, but if you set it to dark it saves it in the user settings, but if your environment is blow away, that goes away.  I don't know if we can do anything about this because lab has to load before our extensions load, but we might be able to do something like we save user preferences right now it would require some digging.

We would need to save it in ~/.jupyterlab/user-settings/@jupyterlab/apputils-extension/themes.jupyterlab-settings
{
    "theme": "JupyerLab Dark"
}

but I would have to figure out how our extension accesses that.

**Comment by mcrutch** [comment]
We now have a way for a user's preferences to be remembered (although it doesn't support autoloading at this time because the UI would still need to be reloaded for the changes to take affect anyway) BUT this allows them to save ALL of their settings from Jupyterlab. Themes, font-sizes, etc.. It does NOT support tracking custom extensions they have installed, but any of the settings could still be stored/pulled down.
